export const articleImages: Record<string, { src: string; alt: string; caption: string }> = {
  'guides/how-to-fix-septic-drain-field': { src: '/images/how-to-fix-septic-drain-field.webp', alt: "Septic drain field repair guide illustration showing damaged pipes, saturated soil, professional inspection and repair options.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-drain-field-replacement-cost': { src: '/images/septic-drain-field-replacement-cost.webp', alt: "Septic drain field replacement cost illustration highlighting soil conditions, permits, materials, excavation and labor.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-inspection-cost': { src: '/images/septic-inspection-cost.webp', alt: "Septic inspection cost illustration showing tank access, inspection report, filters, pumps and drain field evaluation.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-tank-alarm-going-off': { src: '/images/septic-tank-alarm-going-off.webp', alt: "Septic tank alarm troubleshooting illustration showing a high-water alarm, power outage, heavy rain and pump issues.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/clogged-septic-drain-field': { src: '/images/clogged-septic-drain-field.webp', alt: "Clogged septic drain field illustration showing slow drains, wet yard, blocked line and normal versus troubled drainage.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/signs-septic-tank-is-full': { src: '/images/septic-tank-warning-signs.webp', alt: "Signs of a full septic tank illustration with slow drains, gurgling toilet, odors, wet yard and septic alarm.", caption: 'Warning signs can involve the tank, house plumbing or drain field; an inspection identifies the cause.' },
  'guides/how-septic-system-works': { src: '/images/how-septic-system-works.png', alt: 'Illustrated house connected to a septic tank and drain field, showing the main parts of a conventional septic system.', caption: 'From the house to the tank and drain field: the main parts of a conventional septic system.' },
  maintenance: { src: '/images/septic-tank-maintenance.png', alt: 'Septic system illustration with a maintenance checklist for planning service dates, keeping records and protecting the drain field.', caption: 'A manageable routine: plan the service date, keep the records and protect the drain field.' },
  problems: { src: '/images/septic-tank-problems.png', alt: 'House and septic tank illustration with a symptom checklist for smells, slow drains and alarms.', caption: 'Start with the symptoms you notice, then choose the next step.' }
};
