export const articleImages: Record<string, { src: string; alt: string; caption: string }> = {
  'guides/how-to-fix-septic-drain-field': { src: '/images/how-to-fix-septic-drain-field.webp', alt: "Illustration of septic tank and household wastewater system accompanying guidance on how to fix a septic drain field: problems, repair options and costs.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-drain-field-replacement-cost': { src: '/images/septic-drain-field-replacement-cost.webp', alt: "Illustration of septic tank and household wastewater system accompanying guidance on septic drain field replacement cost: what changes the price?.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-inspection-cost': { src: '/images/septic-inspection-cost.webp', alt: "Illustration of septic tank and household wastewater system accompanying guidance on septic inspection cost: what is included and who pays?.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/septic-tank-alarm-going-off': { src: '/images/septic-tank-alarm-going-off.webp', alt: "Illustration of septic tank and household wastewater system accompanying guidance on septic tank alarm going off? what to do first.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/clogged-septic-drain-field': { src: '/images/clogged-septic-drain-field.webp', alt: "Illustration of septic tank and household wastewater system accompanying guidance on clogged septic drain field: signs, causes and next steps.", caption: "Practical septic advice: understand symptoms, ask for a diagnosis and keep service records." },
  'guides/signs-septic-tank-is-full': { src: '/images/septic-tank-warning-signs.webp', alt: 'Illustration of a home septic system with warning symptoms including slow drains, odors and alarms.', caption: 'Warning signs can involve the tank, house plumbing or drain field; an inspection identifies the cause.' },
  'guides/how-septic-system-works': { src: '/images/how-septic-system-works.png', alt: 'Illustrated house connected to a septic tank and drain field, showing the main parts of a conventional septic system.', caption: 'From the house to the tank and drain field: the main parts of a conventional septic system.' },
  maintenance: { src: '/images/septic-tank-maintenance.png', alt: 'Septic system illustration with a maintenance checklist for planning service dates, keeping records and protecting the drain field.', caption: 'A manageable routine: plan the service date, keep the records and protect the drain field.' },
  problems: { src: '/images/septic-tank-problems.png', alt: 'House and septic tank illustration with a symptom checklist for smells, slow drains and alarms.', caption: 'Start with the symptoms you notice, then choose the next step.' }
};
