import { articles } from './articles';
export const tools=[
 {slug:'septic-tank-size-calculator',kind:'tank',title:'Septic Tank Size Calculator',description:'Compare household water use and a Minnesota tank-capacity reference. Start with your bedrooms, household size and system details.',method:'Daily wastewater = people × gallons used per person. The two-day view is a water-volume illustration, not a required tank size. Minnesota mode uses Rule 7080.1930 bedroom tiers and applies the disposal/ejector adjustment once. Confirm installation capacity locally.',sources:['epa-care','mn-capacity']},
 {slug:'septic-pumping-frequency-calculator',kind:'frequency',title:'Septic Pumping Frequency Calculator',description:'Find your next septic tank pumping window from the last service date. Save your schedule or download a calendar reminder.',method:'The calculator adds your selected interval to the last pumping date. The default is three to five years; change it to follow your provider’s advice. Tank size and household details are recorded with the plan but do not change the date calculation.',sources:['epa-care','epa-faq']},
 {slug:'septic-pumping-cost-calculator',kind:'cost',title:'Septic Tank Pumping Cost Calculator',description:'Estimate the total of a septic pumping quote, including access fees, disposal charges, emergency service and tax.',method:'The calculator totals your quoted pumping price and extra charges, then applies the selected tax rate to the subtotal. If only some items are taxable, enter zero percent and add the quoted tax as a fee. Avoid entering fees already included in the base price.',sources:[]},
 {slug:'septic-troubleshooter',kind:'troubleshooter',title:'Septic System Troubleshooter: Smells, Backups & Slow Drains',description:'Check septic tank smells, gurgling toilets, slow drains, alarms and wet yards. Get a clear next step for your symptoms.',method:'The troubleshooter prioritizes sewage backups and possible surfacing, flags alarms for service, and helps you describe other persistent symptoms. A local provider can check the cause.',sources:['epa-failure']}
] as const;
export const pages:Record<string,{title:string;description:string;sections:[string,string][];sourceIds?:string[]}>= {
 'about':{title:'About SepticHow',description:'A clearer starting point for septic homeowners.',sections:[['Why we exist','SepticHow is an independent information and planning project for US homeowners. Our calculators and guides help you understand septic tanks, plan pumping and find the next step when drains or alarms cause trouble.'],['Who is behind the project','The project is owned by Jaspal Singh and operated from India. We publish homeowner guides and free planning tools, using public agency and university references.'],['What you can expect','Free calculators, clear explanations, practical checklists and links to reliable references.']]},
 'editorial-policy':{title:'Editorial policy',description:'How guidance earns its place on SepticHow.',sections:[['Evidence before claims','We prioritize environmental agencies, published state rules and university extension sources. Manufacturer instructions are used for specific equipment. A commercial article alone does not establish an engineering or regulatory requirement.'],['Clear attribution','Each source-backed page identifies references and the date we checked them. National guidance is kept separate from jurisdiction-specific rules. Calculations distinguish referenced inputs from our own illustrative assumptions.'],['Review and corrections','We do not claim professional review where none has occurred. Proposed changes to numeric rules must include the relevant official reference. AI-assisted drafting is checked against cited sources before publication.']]},
 'methodology':{title:'How Our Septic Calculators Work',description:'See how our tank water-use, pumping schedule and pumping cost calculators use the details you enter.',sections:[['Tank planning','General mode multiplies household members by daily water use and shows a two-day liquid-volume illustration. Minnesota mode adds the bedroom-based capacity reference in Rule 7080.1930. Confirm installation requirements with your local permitting office.'],['Pumping schedule','The tool adds your selected interval to the last pumping date. Tank capacity and household size stay with the plan as context. Use your provider’s recommended interval and update the plan after inspections.'],['Pumping budget','The tool adds your quoted pumping price and extra charges, then applies an optional tax rate to the subtotal. Use local written quotes when comparing service budgets.'],['Version and source dates','Calculator method v1.0. Content updated October 5, 2026. Reference dates appear in the source library.']]},
 'corrections':{title:'Report a correction',description:'Help us keep facts and assumptions checkable.',sections:[['Prepare a useful report','Include the page URL, the specific statement or result, what you believe is incorrect, and a supporting official source. Do not include addresses, permit numbers or other private property information.'],['Current contact route','A dedicated SepticHow corrections inbox has not been configured yet. Until it is available, corrections can be reported to the project owner through the channel where this project was shared. Public launch requires an operational contact route.']]},
 'disclaimer':{title:'Planning and information disclaimer',description:'Understand the limits before acting on a result.',sections:[['Not an approved design','Calculators provide arithmetic illustrations or explicitly scoped source references. They are not installation plans, permitting advice, engineering services, inspection reports or contractor quotations.'],['Local decisions','Your permitting authority and appropriately qualified professionals determine applicable requirements and site suitability. Do not buy equipment or start work solely from this website.'],['Urgent symptoms','Wastewater backup or surfacing requires prompt professional attention. Avoid contact with sewage and never enter a septic tank. An online tool cannot determine whether your system is safe.']]},
 'privacy':{title:'Privacy',description:'A small, straightforward launch site.',sections:[['Calculator inputs','Our calculators run in your browser. Inputs are not submitted to an application database. Choosing Save stores a schedule in this browser’s local storage. You can delete it with the Delete saved plan button. Clearing browser data also removes it.'],['Hosting and links','The web host may process request metadata, including IP address and requested URLs, for delivery and security. External source links lead to third-party websites with their own policies.'],['Analytics, advertising and email','This launch build does not include advertising scripts, analytics trackers or email reminders. We will update this policy and any required consent controls before adding those services. Browser-local calendar downloads do not send email.']]},
 'terms':{title:'Terms of use',description:'Use SepticHow as a starting point for informed planning.',sections:[['Using the tools','You are responsible for checking your inputs and confirming assumptions with your service provider or permitting authority. Website information may be incomplete for your location or system.'],['Content and sources','Original SepticHow text, layouts and illustrations belong to the project. Linked public sources remain the work of their respective publishers. We do not imply agency endorsement.'],['Availability and updates','Tools and assumptions may change as the project develops. Keep your original service records; this website is not a permanent maintenance-record repository.']]},
 'guides/how-septic-system-works':{title:'How Does a Septic System Work?',description:'Learn how a septic tank, drain field and soil treat household wastewater in a conventional septic system.',sections:[['From the house to the tank','Wastewater enters the tank, where heavier solids settle and lighter material floats. This separation helps keep solids out of the drain field.'],['From the tank to the soil','Liquid effluent moves through the distribution system to the drain field. The field and suitable soil provide further treatment. A conventional layout is only one system type; your permit identifies what was installed.'],['Keep the records','Find your installation drawing, tank capacity and service reports. These are more useful to a service professional than a generic diagram.']],sourceIds:['epa-faq']},
 'maintenance':{title:'Septic Tank Maintenance: Pumping, Care & Service Schedule',description:'Learn how to maintain a septic system, plan pumping, reduce avoidable problems and keep useful service records.',sections:[['Make your next service visible','Use the pumping-frequency tool to organize a planning window. Save the last pumping date, tank capacity and provider’s recommended interval.'],['Everyday habits','Limit unnecessary water use, spread laundry loads and keep vehicles off the drain field. Maintain your system according to the service provider’s instructions.']],sourceIds:['epa-care']},
 'problems':{title:'Septic Tank Problems: Smells, Slow Drains, Backups & Wet Yard',description:'Check common signs of septic trouble, including bad smells, slow drains, sewage backup, alarms and wet areas near the drain field.',sections:[['Record the symptom','Note when the problem began, which fixtures are affected and whether an alarm or outdoor wet area is present. Use the troubleshooter for an initial next-step checklist.'],['Do not wait on sewage','If wastewater backs up or appears at the surface, reduce water use, avoid contact and seek professional assistance promptly.']],sourceIds:['epa-failure']}
};

// Keep existing public URLs while using the expanded homeowner articles.
for (const [path, article] of Object.entries(articles)) {
  pages[path] = { title: article.title, description: article.description, sections: [], sourceIds: article.sourceIds };
}
