import type { FAQ } from './articles';
export type ToolGuidance = { sections: { title: string; paragraphs: string[]; steps?: string[] }[]; faqs: FAQ[]; related: { href: string; label: string }[] };
export const toolGuidance: Record<string, ToolGuidance> = {
  'septic-tank-size-calculator': {
    sections: [
      { title: 'What size septic tank do I need for my house?', paragraphs: ['Start with the number of bedrooms, your installation records and the requirements where the home is located. If you already have a septic system, the permit or pumping report may identify its tank capacity. If you are planning a replacement, take those records to the designer or permitting office before choosing equipment.', 'This free septic tank size calculator has two views. General mode shows estimated daily household wastewater and a two-day liquid-volume illustration. Minnesota mode also shows a bedroom-based capacity reference under Rule 7080.1930. Keep these results separate: household water use is not the same as an approved minimum tank size.'] },
      { title: 'How to use the septic tank size calculator', paragraphs: ['Enter household details you know, then choose the reference mode that applies to your question. The water-use figure is editable so you can compare scenarios, such as a larger household or lower water use.'], steps: ['Enter the bedroom count and number of household members.', 'Review the gallons-per-person figure and change it if needed.', 'Choose general water-use planning or the Minnesota capacity reference.', 'Select disposal or ejector use where relevant.', 'Calculate, then keep the household-flow result separate from any state-rule capacity.'] },
      { title: 'Septic tank size for a three-bedroom or four-bedroom house', paragraphs: ['A bedroom-based search is a useful starting point, but requirements vary by location. The Minnesota reference in this tool should not be applied to every state. For a home elsewhere, ask the local office what capacity rule and design information are required.', 'For example, four people using the entered 70 gallons each per day produce a 280-gallon daily-flow scenario. The two-day illustration is 560 gallons of liquid volume. That 560-gallon figure is not a recommendation to buy a 560-gallon tank. Use it to understand the arithmetic and discuss the household’s use.'] },
      { title: 'Tank capacity and household water use are different questions', paragraphs: ['Tank capacity is the size of the installed tank. Daily wastewater is how much water the household sends through the system. Keeping both numbers on your service notes makes the conversation clearer. A report identifying a 1,000-gallon tank does not mean the home produces 1,000 gallons every day.', 'If the question is when to pump an existing tank, use the pumping schedule tool with your last service date and recommended interval. If the question is whether a replacement design will be approved, use the property records and local design process.'] }
    ],
    faqs: [
      { question: 'Does this calculator tell me the minimum tank size in every state?', answer: 'No. General mode shows water-use arithmetic. The separate capacity reference applies to Minnesota Rule 7080.1930; other locations have their own requirements.' },
      { question: 'Where can I find my existing septic tank size?', answer: 'Check the permit, installation drawing, inspection report or pumping records. The company that last serviced the system may also have the capacity on file.' },
      { question: 'Does a garbage disposal affect septic tank sizing?', answer: 'It can affect the applicable requirements and service needs. The Minnesota reference applies its specified 50% adjustment once when a disposal or ejector is selected.' },
      { question: 'Can I compare water use for two people and four people?', answer: 'Yes. Change the household member count and compare the daily-flow results. Keep the same per-person input if you want the comparison to show only the change in occupancy.' }
    ],
    related: [{ href: '/guides/how-septic-system-works', label: 'How a septic tank and drain field work' }, { href: '/tools/septic-pumping-frequency-calculator', label: 'Plan the next pumping date' }]
  },
  'septic-pumping-frequency-calculator': {
    sections: [
      { title: 'How often should you pump your septic tank?', paragraphs: ['A typical household pumping interval is three to five years under EPA guidance, but your system’s inspection findings and provider’s advice determine the right schedule. Use the interval recommended for your home when it differs from the default.', 'This septic pumping frequency calculator turns a last pumping date and selected interval into a service window. It also lets you record tank capacity and household size with the plan. Those details help the service conversation; the date calculation uses the interval you enter.'] },
      { title: 'How to calculate your next septic pumping date', paragraphs: ['Have the last pumping receipt or service report nearby so you start with a reliable date. If you cannot find a date, arrange a professional assessment rather than inventing one.'], steps: ['Enter the last pumping date from your records.', 'Add tank capacity, household size and system type.', 'Use the recommended earliest and latest intervals, or keep the default three-to-five-year window.', 'Calculate the dates and review whether the window is current or overdue.', 'Save the plan in this browser or download a calendar reminder.'] },
      { title: 'How often to pump a 1,000-gallon septic tank', paragraphs: ['The capacity alone does not settle the pumping schedule. A provider also considers the household’s use and the condition found during inspection. Keep the tank size on the plan, then enter the interval recommended for that system.', 'For example, if a tank was pumped in October 2023 and you select a three-to-five-year interval, the planning window runs from October 2026 to October 2028. If an inspection recommends an earlier visit, change the interval. The calendar should follow the current service advice.'] },
      { title: 'When to review the schedule sooner', paragraphs: ['More people moving into the home, a change in property use or a new service recommendation are reasons to review the plan. Systems with pumps or treatment equipment can also have inspection dates separate from the pumping date.', 'Do not wait for a saved reminder if sewage backs up, wastewater may be surfacing or an alarm needs attention. Use the troubleshooter for an immediate next-step checklist and contact the appropriate provider. A reminder is for routine planning, not handling a current problem.'] }
    ],
    faqs: [
      { question: 'Does tank size automatically change the date in this calculator?', answer: 'No. The date is calculated from the last pumping date and the interval you choose. Tank size and household details are saved as context for your provider.' },
      { question: 'Can I save my septic pumping schedule?', answer: 'Yes. Save stores it in this browser on this device. You can also download a calendar reminder and keep your original service reports separately.' },
      { question: 'Does an overdue date mean my septic system has failed?', answer: 'No. It means your selected service window has passed. Arrange service advice and consider any current symptoms rather than treating the date as a diagnosis.' },
      { question: 'Should I use the default schedule for an aerobic system?', answer: 'Follow the equipment instructions and service contract. Pumping and equipment inspections can have different schedules, so record both.' }
    ],
    related: [{ href: '/maintenance', label: 'Septic maintenance checklist' }, { href: '/my-septic-schedule', label: 'Save a septic maintenance reminder' }, { href: '/problems', label: 'Septic warning signs that should not wait' }]
  },
  'septic-pumping-cost-calculator': {
    sections: [
      { title: 'How much does septic tank pumping cost?', paragraphs: ['The most useful budget starts with a written local quote. Ask which tanks and services are included and whether access, disposal, emergency work or taxes cost extra. Compare the total scope as well as the advertised base price.', 'This septic tank pumping cost calculator adds the prices you enter. It is designed for checking a quote or comparing two itemized budgets. Enter the company’s actual charges rather than assuming a nationwide average is the price for your property.'] },
      { title: 'How to estimate the total cost of a pumping quote', paragraphs: ['Keep the quote open while entering each charge. If a fee is already included in the base price, leave its separate box at zero so it is not counted twice.'], steps: ['Enter the quoted base pumping price.', 'Add any access or digging charge.', 'Add disposal or other separately quoted fees.', 'Include an emergency surcharge if one applies.', 'Enter the applicable tax rate, or leave tax at zero and include the quoted tax as a fee when appropriate.'] },
      { title: 'A simple septic pumping budget example', paragraphs: ['Suppose a quote lists $400 for pumping, $50 for access and $25 for a separately billed fee. The subtotal is $475. If an 8% tax applies to the whole subtotal, the tax is $38 and the total is $513. These are example inputs to explain the calculator, not market prices.', 'For another quote, change the inputs and compare what each provider includes. A lower base price may come with charges that appear later. Record the quoted tank capacity or pumping allowance, access arrangements and any included inspection work alongside the total.'] },
      { title: 'Questions to ask before booking septic pumping', paragraphs: ['Ask whether the price covers all required tanks, what happens if the lids are buried and whether a written service report is included. If you are booking because of a backup, make that clear: a routine pumping quote may not include diagnosis, repairs or contamination cleanup.', 'Keep repair prices separate from the pumping budget unless the quote explicitly includes them. After service, save the final invoice and next recommended interval. Those details give you a better starting point when planning the next visit.'] }
    ],
    faqs: [
      { question: 'Does this calculator show pumping prices near me?', answer: 'It totals a quote you enter; it does not retrieve local contractor prices. Ask providers for written quotes and use the calculator to compare complete totals.' },
      { question: 'What if disposal fees are already included?', answer: 'Leave the separate fee input at zero. Add only charges that are not already part of the base price.' },
      { question: 'How does the tax calculation work?', answer: 'The selected percentage applies to the whole subtotal. If the quote taxes only some items, enter zero percent and include the quoted tax amount as a separate fee.' },
      { question: 'Are emergency septic repairs included in the total?', answer: 'Only the amounts you enter are included. Ask for a separate written repair scope where work goes beyond pumping and the stated service extras.' }
    ],
    related: [{ href: '/maintenance', label: 'Prepare for a septic pumping visit' }, { href: '/tools/septic-pumping-frequency-calculator', label: 'Plan when to arrange pumping' }, { href: '/problems', label: 'What to do when a septic problem is urgent' }]
  },
  'septic-troubleshooter': {
    sections: [
      { title: 'What is wrong with my septic system?', paragraphs: ['Start with the symptom you can observe. A sewage smell, gurgling toilet, slow drain, alarm or wet patch gives you something concrete to describe. The septic system troubleshooter helps organize those details and choose a next step.', 'If wastewater is backing up indoors or may be surfacing outside, reduce water use, keep people away and arrange prompt professional help. Do not open a tank, bypass controls or try to handle sewage while checking symptoms.'] },
      { title: 'How to use the septic troubleshooter', paragraphs: ['Select the main symptom, then add the information that applies. Report sewage backups and possible surfacing even if another symptom was the first thing you noticed.'], steps: ['Choose alarm, backup, odor, slow drains, wet yard or gurgling.', 'Mark any indoor wastewater backup or possible outdoor surfacing.', 'Record recent heavy rain where relevant.', 'Read the next step and collect safe, visible information for the call.', 'Contact a plumber or septic provider with the symptoms and service history.'] },
      { title: 'Septic tank smells, slow drains and gurgling toilets', paragraphs: ['Note whether one fixture or several are affected and where a smell is strongest. Tell the provider when the issue started and whether it occurs during laundry, showers or other water use. Avoid assuming that every symptom means pumping is the only answer.', 'For example, “the downstairs toilet gurgles when the washing machine drains” gives the professional a clearer starting point than “the septic tank is full.” Add the last service date and any alarm information if available.'] },
      { title: 'Septic alarms and problems after heavy rain', paragraphs: ['For an alarm, read the visible indicator and keep the equipment manual nearby. Contact the service provider for that system. Do not treat silencing an alarm as a repair.', 'After rain, explain both the weather and the symptoms. A wet yard does not identify the cause on its own. Observe from a safe place and ask the provider which checks are needed before deciding to book pumping or another specific job.'] }
    ],
    faqs: [
      { question: 'Can the troubleshooter diagnose a failed drain field?', answer: 'It helps choose a next step from symptoms. A professional assessment is needed to identify the cause and condition of the drain field.' },
      { question: 'What if sewage is backing up right now?', answer: 'Reduce wastewater use, avoid sewage contact and arrange prompt professional help. Keep people and pets away from the affected area.' },
      { question: 'What should I tell the service company?', answer: 'Describe the symptom, when it started, which fixtures are affected, any visible alarm details and the last service date. Mention rain or unusual water use as context.' },
      { question: 'Should I pump the tank when an alarm sounds?', answer: 'Contact the equipment service provider first. The alarm needs the appropriate checks, and pumping may not be the required or complete response.' }
    ],
    related: [{ href: '/problems', label: 'Read the full septic problems guide' }, { href: '/maintenance', label: 'Create a routine maintenance plan' }, { href: '/guides/how-septic-system-works', label: 'Understand the tank and drain field' }]
  }
};
